# Use 4.20 as the base
# 4.20.0 release image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f9d1f649ed9bc155cd6b43aa43a606846b996b6577a7bcc3d872a91e415abc98

ARG OCP_RELEASE_IMAGE=quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:f9d1f649ed9bc155cd6b43aa43a606846b996b6577a7bcc3d872a91e415abc98

FROM ${OCP_RELEASE_IMAGE}

RUN --mount=type=secret,id=org,dst=/run/secrets/org \
    --mount=type=secret,id=key,dst=/run/secrets/key \
    set +x && \
    subscription-manager register \
      --org=$(cat /run/secrets/org) \
      --activationkey=$(cat /run/secrets/key)

WORKDIR /

# Install Kernel, Qemu and Kata-containers and initrds
COPY tdx/rhel-9_7.repo /etc/yum.repos.d
COPY snp/rpms/ /

RUN \
  if [ -s /list_rpms_replace ]; then \
    echo "--- Replacing RPMs specified in /list_rpms_replace ---" && \
    rpm-ostree override replace $(cat /list_rpms_replace); \
  else \
    echo "--- Skipping RPM replacement: /list_rpms_replace is empty or not found ---"; \
  fi && \
  if [ -s /list_rpms_install ]; then \
    echo "--- Installing RPMs specified in /list_rpms_install ---" && \
    rpm-ostree install $(cat /list_rpms_install); \
  else \
    echo "--- Skipping RPM installation: /list_rpms_install is empty or not found ---"; \
  fi


# Selinux adjustments to provide access to sev
RUN setsebool -P container_use_devices 1

RUN rpm-ostree cleanup -m && \
    ostree container commit
